lidarts/profile/forms.py
from flask import url_for
from flask_babelex import lazy_gettext
from flask_wtf import FlaskForm
from wtforms import BooleanField, SelectField, SubmitField, IntegerField, TextAreaField, StringField, PasswordField
from wtforms.validators import DataRequired, NumberRange, Length, Regexp
from lidarts.profile.countries import COUNTRIES

enabled_disabled = [('enabled', lazy_gettext('Enabled')), ('disabled', lazy_gettext('Disabled'))]


class EditProfileForm(FlaskForm):
    bio = TextAreaField(lazy_gettext('Description'), validators=[Length(min=0, max=2000)])
    submit = SubmitField(lazy_gettext('Save'))


class ChangeCallerForm(FlaskForm):
    callers = SelectField(lazy_gettext('Caller'), validators=[DataRequired()])
    submit = SubmitField(lazy_gettext('Save'))


class ChangeCPUDelayForm(FlaskForm):
    delay = IntegerField(lazy_gettext('Trainer delay'), validators=[DataRequired(), NumberRange(0, 30)])
    submit = SubmitField(lazy_gettext('Save'))


class GeneralSettingsForm(FlaskForm):
    notification_sound = SelectField(
        lazy_gettext('Notification sound'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    allow_challenges = SelectField(
        lazy_gettext('Allow challenges'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    allow_private_messages = SelectField(
        lazy_gettext('Allow private messages'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    allow_friend_requests = SelectField(
        lazy_gettext('Allow friend requests'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    checkout_suggestions = SelectField(
        lazy_gettext('Checkout suggestions'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    show_average_in_chat_list = SelectField(
        lazy_gettext('Show averages in user list'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    submit = SubmitField(lazy_gettext('Save'))


class ChangeCountryForm(FlaskForm):
    country = SelectField(
        lazy_gettext('Country'),
        choices=COUNTRIES,
        validators=[DataRequired()],
    )

    accept_country_cooldown = BooleanField(lazy_gettext('Accept'), validators=[DataRequired()])

    submit = SubmitField(lazy_gettext('Save'))


class WebcamSettingsForm(FlaskForm):
    activated = SelectField(
        lazy_gettext('Webcam activated'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    stream_consent = SelectField(
        lazy_gettext('Allow streaming'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    mobile_app = SelectField(
        lazy_gettext('Use Jitsi mobile app'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    mobile_follower_mode = SelectField(
        lazy_gettext('Mobile follow mode'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    force_scoreboard_page = SelectField(
        lazy_gettext('Show only scoreboard on main device'),
        choices=enabled_disabled,
        validators=[DataRequired()],
    )

    jitsi_public_server = BooleanField(lazy_gettext('Use public Jitsi server'))

    submit = SubmitField(lazy_gettext('Save'))


class LivestreamSettingsForm(FlaskForm):
    channel_id = StringField(lazy_gettext('Channel ID'), validators=[Length(min=15, max=30), Regexp('^UC\w+$')])
    submit = SubmitField(lazy_gettext('Save'))


class CloseAccountForm(FlaskForm):
    password = PasswordField(lazy_gettext('Enter Password'), validators=[DataRequired()])
    submit = SubmitField(lazy_gettext('Close account permanently'))

lidarts/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from lidarts.profile import routes

lidarts/profile/routes.py
from flask import render_template, url_for, jsonify, redirect, flash, current_app, request
from flask_babelex import lazy_gettext
from flask_login import current_user, login_required
from flask_security.utils import verify_password
from lidarts import db, avatars
from lidarts.generic.forms import UserSearchForm
from lidarts.profile import bp
from lidarts.profile.forms import (ChangeCallerForm, ChangeCPUDelayForm, GeneralSettingsForm, ChangeCountryForm, 
    EditProfileForm, WebcamSettingsForm, LivestreamSettingsForm, CloseAccountForm)
from lidarts.models import (Caller, User, CricketGame, Game, Friendship, 
    FriendshipRequest, UserSettings, UserStatistic, WebcamSettings,
    Chatmessage, ChatmessageIngame, Privatemessage)
from sqlalchemy import desc
from sqlalchemy.orm import aliased
from lidarts.utils.linker import linker
import bleach
import os
from PIL import Image
import re
import time
from datetime import datetime, timedelta
from sqlalchemy import func


@bp.route('/@/<username>/game_history')
@login_required
def game_history(username):
    page = request.args.get('page', 1, type=int)

    user = User.query.filter_by(username=username).first_or_404()

    games = Game.query.filter(((Game.player1 == user.id) | (Game.player2 == user.id)) & (Game.status == 'completed')) \
        .order_by(desc(Game.id))

    games = games.paginate(page, 10, False)
    next_url = url_for('profile.game_history', username=username, page=games.next_num) \
        if games.has_next else None
    prev_url = url_for('profile.game_history', username=username, page=games.prev_num) \
        if games.has_prev else None

    player_names = {}
    for game in games.items:
        if game.player1 and game.player1 not in player_names:
            player_names[game.player1] = User.query.with_entities(User.username) \
                .filter_by(id=game.player1).first_or_404()[0]
        if game.player2 and game.player2 not in player_names:
            player_names[game.player2] = User.query.with_entities(User.username) \
                .filter_by(id=game.player2).first_or_404()[0]

    return render_template('profile/game_history.html', games=games.items, user=user, player_names=player_names,
                           next_url=next_url, prev_url=prev_url, title=lazy_gettext('Match History'))


@bp.route('/@/')
@bp.route('/@/<username>')
@login_required
def overview(username):
    player_names = {}
    user = User.query.filter(func.lower(User.username)  == func.lower(username)).first()
    if not user:
        return redirect(url_for('profile.user_not_found', username=username))
    player1 = aliased(User)
    player2 = aliased(User)
    games = (
        Game.query
        .filter(
            ((Game.player1 == user.id) | (Game.player2 == user.id)) & (Game.status != 'challenged')
            & (Game.status != 'declined') & (Game.status != 'aborted')
        )
        .join(player1, Game.player1 == player1.id).add_columns(player1.username)
        .join(player2, Game.player2 == player2.id, isouter=True).add_columns(player2.username)
        .order_by(desc(Game.id)).limit(10).all()
    )

    cricket_games = (
        CricketGame.query
        .filter(
            ((CricketGame.player1 == user.id) | (CricketGame.player2 == user.id)) & (CricketGame.status != 'challenged')
            & (CricketGame.status != 'declined') & (CricketGame.status != 'aborted')
        )
        .join(player1, CricketGame.player1 == player1.id).add_columns(player1.username)
        .join(player2, CricketGame.player2 == player2.id, isouter=True).add_columns(player2.username)
        .order_by(desc(CricketGame.id)).limit(10).all()
    )
    games.extend(cricket_games)
    games.sort(key=lambda game: game[0].begin, reverse=True)

    stats = UserStatistic.query.filter_by(user=user.id).first()
    if not stats:
        stats = UserStatistic(user=user.id)
        db.session.add(stats)
        db.session.commit()

    settings = (
        UserSettings.query
        .with_entities(UserSettings.country, UserSettings.profile_text)
        .filter_by(user=user.id)
        .first()
    )

    if not settings:
        settings = UserSettings(user=user.id)
        db.session.add(settings)
        db.session.commit()
        country = None
        profile_text = None
    else:
        country, profile_text = settings


    if profile_text:
        profile_text = re.sub(
            r'(\bhttps:\/\/i\.imgur\.com\/\w+.\w+)',
            '<img src="' + r'\1' + '" style="max-width: 100%">',
            profile_text,
        )
        profile_text = linker.linkify(profile_text)
        profile_text = profile_text.replace('\n', '<br>')
        
    friend_query1 = Friendship.query.with_entities(Friendship.user2_id).filter_by(user1_id=current_user.id)
    friend_query2 = Friendship.query.with_entities(Friendship.user1_id).filter_by(user2_id=current_user.id)

    friend_list = friend_query1.union(friend_query2).all()
    friend_list = [r for (r,) in friend_list]

    avatar_url = avatars.url(f'{user.id}_thumbnail.jpg') if user.avatar else avatars.url('default.png')

    return render_template('profile/overview.html', user=user, games=games[:10],
                           player_names=player_names, friend_list=friend_list,
                           recently_online=user.recently_online(),
                           country=country, profile_text=profile_text,
                           stats=stats, avatar_url=avatar_url, title=lazy_gettext('Profile'))


@bp.route('/edit_profile/', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    user_settings = (
        UserSettings.query
        .filter_by(user=current_user.id)
        .first()
    )
    if form.validate_on_submit():
        bio_cleaned = bleach.clean(form.bio.data)
        user_settings.profile_text = bio_cleaned
        db.session.commit()
        flash(lazy_gettext('Profile text saved.'))
    if user_settings.profile_text:
        form.bio.data = user_settings.profile_text

    return render_template('profile/edit_profile.html', form=form)


@bp.route('/set_status/')
@bp.route('/set_status/<status>', methods=['POST'])
@login_required
def set_status(status):
    user = User.query.filter_by(id=current_user.id).first_or_404()
    user.status = status
    db.session.commit()
    return jsonify('success')


@bp.route('/user-not-found', methods=['POST'])
@bp.route('/user-not-found/<string:username>', methods=['GET', 'POST'])
@login_required
def user_not_found(username):
    form = UserSearchForm()
    if form.validate_on_submit():
        return redirect(url_for('profile.overview', username=form.username.data).replace('%40', '@'))
    return render_template('profile/user_not_found.html', username=username, form=form)


@bp.route('/manage_friend_list')
@login_required
def manage_friend_list():
    player_names = {}

    friend_query1 = Friendship.query.with_entities(Friendship.user2_id).filter_by(user1_id=current_user.id)
    friend_query2 = Friendship.query.with_entities(Friendship.user1_id).filter_by(user2_id=current_user.id)

    friend_list = friend_query1.union(friend_query2).all()
    friend_list = [r for (r,) in friend_list]

    for friend in friend_list:
        if friend and friend not in player_names:
            player_names[friend] = User.query.with_entities(User.username) \
                .filter_by(id=friend).first_or_404()[0]

    friendship_request = FriendshipRequest.query.with_entities(FriendshipRequest.receiving_user_id) \
        .filter_by(requesting_user_id=current_user.id).all()

    friendship_request = [r for (r,) in friendship_request]

    for request in friendship_request:
        if request and request not in player_names:
            player_names[request] = User.query.with_entities(User.username) \
                .filter_by(id=request).first_or_404()[0]

    player_names_sorted = {k: v for k, v in sorted(player_names.items(), key=lambda x: x[1])}
    friend_list.sort(key=lambda k: player_names_sorted[k])

    return render_template('profile/manage_friend_list.html',
                           friend_list=friend_list, player_names=player_names, pending_requests=friendship_request,
                           title=lazy_gettext('Manage Friend List'))


@bp.route('/delete_avatar', methods=['GET', 'POST'])
@login_required
def delete_avatar():
    if current_user.avatar:
        try:
            os.remove(os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'avatars', current_user.avatar))
            os.remove(os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'avatars', f'{current_user.id}_thumbnail.jpg'))
        except:
            pass
        flash(lazy_gettext("Avatar deleted."))
    current_user.avatar = None
    db.session.commit()
    return redirect(url_for('profile.change_avatar'))


@bp.route('/change_avatar', methods=['GET', 'POST'])
@login_required
def change_avatar():
    if request.method == 'POST' and 'avatar' in request.files:
        avatar_file = request.files['avatar']
        if avatar_file.filename == '':
            flash(lazy_gettext('No selected file'), 'danger')
            return redirect(request.url)
        delete_avatar()
        filename = avatars.save(avatar_file, name='{}.'.format(current_user.id))
        image = os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'avatars', filename)
        if image.split('.')[-1].lower() not in ['jpg', 'jpeg', 'gif', 'png']:
            flash(lazy_gettext('Wrong image format.'))
            return redirect(url_for('profile.change_avatar'))
        im = Image.open(image)
        rgb_im = im.convert('RGB')
        rgb_im.thumbnail((64, 64), Image.BICUBIC)
        rgb_im.save(os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'avatars', f'{current_user.id}_thumbnail.jpg'), "JPEG")
        current_user.avatar = filename
        current_user.avatar_version = int(time.time())
        db.session.commit()
        flash(lazy_gettext("Avatar saved."))

lidarts/templates/profile/change_avatar.html
{% extends "base.html" %}

{% block app_content %}



<div class="row">
    {% include 'profile/settings.html' %}

    <div class="col-md-8 col-xl-6 order-2">
        <div class="card bg-light text-dark bs-callout bs-callout-info text-center">
            <div class="card-body">
                <h5 class="card-title">Avatar</h5>
                <hr>
                <img src="{{ avatar_url }}">
                <form action="{{ url_for('profile.delete_avatar') }}">
                    <input type="submit" value="{{ _('Delete') }}" class="btn btn-dark mt-3">
                </form>
                <form method="POST" enctype="multipart/form-data" action="{{ url_for('profile.change_avatar') }}">
                    <input type="file" name="avatar" class="form-control-file mt-3 text-center">
                    <input type="submit" class="btn btn-dark mt-3" value="{{ _('Upload') }}">
                </form>

            </div>
        </div>
    </div>

</div>


{% endblock %}

lidarts/templates/profile/change_caller.html
{% extends "base.html" %}

{% block app_content %}



<div class="row">
    {% include 'profile/settings.html' %}

    <div class="col-md-6 col-xl-4 order-2">
        <div class="card bg-light text-dark bs-callout bs-callout-info text-center">
            <div class="card-body">
                <h5 class="card-title">Caller</h5>
                <hr>
                <form method="POST" class="form-horizontal">
                    {{ form.hidden_tag() }}
                    <p>{{ form.callers.label(class="control-label") }}:
                        {{ form.callers(class="form-control custom-select") }}</p>

                    <p>{{ form.submit(class="btn btn-lg btn-info") }}</p>

                    <p>
                        {{ _('Do you want to get yourself as caller option included?') }} 
                        <a href="{{ url_for('generic.contact') }}">{{ _('Contact us!') }}</a>
                    </p>
                </form>

            </div>
        </div>
    </div>

</div>


{% endblock %}

lidarts/templates/profile/change_cpu_delay.html
{% extends "base.html" %}

{% block app_content %}



<div class="row justify-content-center">
    <div class="col-md-10 col-xl-8">
        <div class="card bg-light text-dark bs-callout bs-callout-info text-center">
            <div class="card-body">
                <h5 class="card-title">{{ _('Trainer delay (in seconds)') }}</h5>
                <p>{{ _('Note: There is a base delay of ~3 seconds. The custom delay will be added to this.') }}</p>
                <hr>
                <form method="POST" class="form-horizontal">
                    {{ form.hidden_tag() }}
                    <p>{{ form.delay.label(class="control-label") }}:
                        {{ form.delay(class="form-control") }}</p>
                    {% if form.errors %}
                    {% for error in form.delay.errors %}
                      <p class="font-weight-bold text-danger">{{ error }}</p>
                    {% endfor %}
                  {% endif %}

                    <p>{{ form.submit(class="btn btn-lg btn-info") }}</p>
                </form>

            </div>
        </div>
    </div>

</div>


{% endblock %}

lidarts/templates/profile/close_account.html
{% extends "base.html" %}

{% block app_content %}



<div class="row">
    {% include 'profile/settings.html' %}

    <div class="col-md-8 order-2">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h5 class="card-title text-center">{{ _('Close account') }}</h5>
                <hr>
                <p>{{ _('Closing your account is a permanent decision.') }} <b>{{ _('You will not be able to use your account again.') }}</b></p>
                <form method="POST" class="form-horizontal">
                    {{ form.hidden_tag() }}
                    <p>{{ form.password.label(class="col-form-label") }}
                        {{ form.password(class="form-control") }}</p>
                    {% if form.errors %}
                    {% for error in form.password.errors %}
                      <p class="font-weight-bold text-danger">{{ error }}</p>
                    {% endfor %}
                  {% endif %}

                    <p class="text-right">{{ form.submit(class="btn btn-danger") }}</p>
                </form>

            </div>
        </div>
    </div>

</div>


{% endblock %}

lidarts/templates/profile/edit_profile.html
{% extends "base.html" %}

{% block app_content %}



<div class="row">
    {% include 'profile/settings.html' %}

    <div class="col-md-8 order-2">
        <div class="card bg-light text-dark bs-callout bs-callout-info text-center">
            <div class="card-body">
                <h5 class="card-title">{{ _('Change profile text') }}</h5>
                <hr>
                <form method="POST" class="form-horizontal">
                    {{ form.hidden_tag() }}
                    <p>
                        {{ form.bio(class="form-control", rows="10", column="50", maxlength="2000") }}</p>
                    {% if form.errors %}
                    {% for error in form.bio.errors %}
                      <p class="font-weight-bold text-danger">{{ error }}</p>
                    {% endfor %}
                  {% endif %}
                  <p><small>{{ _('Introduce yourself, your interests, social media etc.') }}</small></p>

                    <p>{{ form.submit(class="btn btn-lg btn-info") }}</p>
                </form>

            </div>
        </div>
    </div>

</div>


{% endblock %}

lidarts/templates/profile/game_history.html
{% extends "base.html" %}

{% block app_content %}

<div class="row justify-content-center">

    <div class="col-md-6 text-center">
        <div class="card bg-light text-dark  bs-callout bs-callout-warning">
            <div class="card-body">
                <h5 class="card-title text-left"><i class="fas fa-history"></i> {{ _('Game history of') }} {{ user.username }}</h5>
                <hr>
                {% for game in games %}
                <a href="{{ url_for('game.start', hashid=game.hashid) }}" style="text-decoration: none;">
                    <div class="card mb-2 match_card">
                        <div class="card-body text-secondary">
                            <h3 class="{%- if game.status == 'started' %}text-started
                                             {%- elif game.player1 != game.player2 and
                                                    ((game.player1 == user.id and game.p1_sets > game.p2_sets)
                                                    or (game.player2 == user.id and game.p2_sets > game.p1_sets))
                                             %}text-success
                                             {%- elif game.player1 != game.player2 and
                                                    ((game.player1 == user.id and game.p1_sets < game.p2_sets)
                                                    or (game.player2 == user.id and game.p2_sets < game.p1_sets))
                                             %}text-danger
                                             {%- elif game.p1_sets == game.p2_sets %}text-warning
                                             {%- else %}text-secondary
                                             {%- endif %}
                                         ">{{ player_names[game.player1] }} {% if game.bo_sets > 1 %}{{ game.p1_sets }}:{{ game.p2_sets }}
                                {% else %}{{ game.p1_legs }}:{{ game.p2_legs }} {% endif %}
                                {%- if game.opponent_type.startswith('computer') %} Trainer {{ game.opponent_type[8:] }}
                                {%- elif game.player1 != user.id or game.player2 != user.id %} {{ player_names[game.player2] }}
                                {%- else %} local guest{% endif %}
                            </h3>

                            <h4 >
                            </h4>

                            <h5>{{ game.type }} {{ game.in_mode }}/{{ game.out_mode }} {% if game.webcam %} <i title="{{ _('Webcam game') }}" class="fas fa-camera"></i>{% endif %}</h5>
                            <h6>                                
                                {{ moment(game.begin).format('DD.MM.YYYY HH:mm') }}
                            </h6>
                        </div>
                    </div>
                </a>
                {% endfor %}



                <ul class="pagination justify-content-center">
                    {% if prev_url %}
                    <li class="page-item">
                        <a class="page-link" href="{{ prev_url | replace('%40', '@') }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">{{ _('Previous') }}</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if next_url %}
                    <li class="page-item">
                        <a class="page-link" href="{{ next_url | replace('%40', '@') }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">{{ _('Next') }}</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>


</div>




{% endblock %}

lidarts/templates/profile/general_settings.html
{% extends "base.html" %}

{% block app_content %}



<div class="row ">
    {% include 'profile/settings.html' %}

    <div class="col-md-6 col-lg-5 col-xl-4 order-2">
        <div class="card bg-light text-dark bs-callout bs-callout-info text-center">
            <div class="card-body">
                <h5 class="card-title">{{ _('General settings') }}</h5>
                <hr>
                <form method="POST" class="form-horizontal">
                    {{ form.hidden_tag() }}
                    <p>
                        {{ form.notification_sound.label(class="control-label") }}:
                        {{ form.notification_sound(class="form-control custom-select") }}
                    </p>

                    <p>
                        {{ form.allow_challenges.label(class="control-label") }}:
                        {{ form.allow_challenges(class="form-control custom-select") }}
                    </p>

                    <p>
                        {{ form.allow_private_messages.label(class="control-label") }}:
                        {{ form.allow_private_messages(class="form-control custom-select") }}
                    </p>

                    <p>
                        {{ form.allow_friend_requests.label(class="control-label") }}:
                        {{ form.allow_friend_requests(class="form-control custom-select") }}
                    </p>

                    <p>
                        {{ form.show_average_in_chat_list.label(class="control-label") }}:
                        {{ form.show_average_in_chat_list(class="form-control custom-select") }}
                    </p>

                    <p>
                        {{ form.checkout_suggestions.label(class="control-label") }}:
                        {{ form.checkout_suggestions(class="form-control custom-select") }}
                    </p>
                    
                    <p>{{ form.submit(class="btn btn-lg btn-info") }}</p>
                </form>

            </div>
        </div>
    </div>

    <div class="col-md-6 col-lg-4 col-xl-4 mt-2 mt-md-0 order-3">
        <div class="card bg-light text-dark bs-callout bs-callout-warning text-center">
            <div class="card-body">
                <h5 class="card-title">{{ _('Country settings') }}</h5>
                <hr>
                <form method="POST" class="form-horizontal">
                    {{ country_form.hidden_tag() }}
                    <p>
                        {{ country_form.country.label(class="control-label") }}:
                        {{ country_form.country(class="form-control custom-select") }}
                    </p>

                    <p>{{ _('You can change your country setting only once per month. Please confirm.') }}</p>
                    <p><div class="custom-control custom-checkbox">
                        {{ country_form.accept_country_cooldown(class="custom-control-input") }}
                        {{ country_form.accept_country_cooldown.label(class="custom-control-label") }}
                        {% if country_form.accept_country_cooldown.errors %}
                        <ul class="errors text-danger">{% for error in country_form.accept_country_cooldown.errors %}<li>{{ error }}</li>{% endfor %}</ul>
                        {% endif %}
                        </div>
                    </p>
                    
                    <p>{{ country_form.submit(class="btn btn-lg btn-info") }}</p>
                </form>

            </div>
        </div>
    </div>

</div>


{% endblock %}

lidarts/templates/profile/livestream_settings.html
{% extends "base.html" %}

{% block app_content %}



<div class="row ">
    {% include 'profile/settings.html' %}

    <div class="col-md-12 col-lg-9 col-xl-8 order-2">
        <div class="card bg-light text-dark bs-callout bs-callout-info text-left">
            <div class="card-body">
                <h5 class="card-title text-center">{{ _('Livestream settings') }}</h5>
                <hr>
                <p>
                    {{ _('You can stream your board in webcam games to spectators. You will need a Google account for YouTube. Log in and copy your Channel ID here:') }}
                    <a href="https://www.youtube.com/account_advanced">https://www.youtube.com/account_advanced</a> 
                    {{ _('and paste it in the box below.') }}
                </p>
                <p>
                    {{ _('There are two options to start a livestream.') }} 
                </p>
                <p>
                    {{ _('You can use the "Start live stream" option in Jitsi Meet which requires the secret stream key. You can find yours here: ') }}
                    <a href="https://www.youtube.com/live_dashboard?nv=1">https://www.youtube.com/live_dashboard</a>. 
                    {{ _('Paste it into the stream key box in Jitsi and click on "Start live stream".') }}
                    {{ _('If you get a "All streamers are currently busy" error Jitsi has no free streamers at the moment. There is nothing Lidarts can do in that case.') }}
                 </p>
                <p>
                    {{ _('The second option is starting a YouTube live stream with an external software. We recommend ') }}
                    <a href="https://obsproject.com">OBS Studio</a>. 
                    {{ _('You can find many tutorials on the internet. It requires some setup work.') }}
               </p>
               <p>
                   {{ _('Livestreams will only be shown if both players allowed to have their games streamed by the other party. You can enable this in the webcam settings.') }}
               </p>

                <form method="POST" class="form-horizontal">
                    {{ form.hidden_tag() }}
                    <p>{{ form.channel_id.label(class="control-label") }}:
                        {{ form.channel_id(class="form-control") }}</p>
                    {% if form.errors %}
                    {% for error in form.channel_id.errors %}
                        <p class="font-weight-bold text-danger">{{ error }}</p>
                    {% endfor %}
                    {% endif %}

                    <p>{{ form.submit(class="btn btn-lg btn-info") }}</p>
                </form>
            </div>
        </div>
    </div>

</div>


{% endblock %}

lidarts/templates/profile/settings.html
{% block settings %}
<div class="col-12 col-lg-3 col-xl-4 order-4 order-lg-1 mt-2 mt-lg-0">
    <div class="card bg-light text-dark ">
        <div class="card-body">
            <p><a href="{{ url_for('profile.general_settings') }}" class="text-secondary">{{ _('General settings') }}</a></p>
            {% if current_user.webcam_settings and current_user.webcam_settings.activated %}
            <p><a href="{{ url_for('profile.webcam_settings') }}" class="text-secondary">{{ _('Webcam settings') }}</a></p>
            <p><a href="{{ url_for('profile.livestream_settings') }}" class="text-secondary">{{ _('Livestream settings') }}</a></p>
            {% else %}
            <p><a href="{{ url_for('game.webcam_consent') }}" class="text-secondary">{{ _('Activate webcam games') }}</a></p>
            {% endif %}
            <p><a href="{{ url_for('profile.edit_profile') }}" class="text-secondary">{{ _('Edit profile text') }}</a></p>
            <p><a href="{{ url_for('profile.manage_friend_list') }}" class="text-secondary">{{ _('Manage friend list') }}</a></p>
            <p><a href="{{ url_for('auth.change_username') }}" class="text-secondary">{{ _('Change display name') }}</a></p>
            <p><a href="{{ url_for_security('change_password') }}" class="text-secondary">{{ _('Change password') }}</a></p>
            <p><a href="{{ url_for('profile.change_avatar') }}" class="text-secondary">{{ _('Avatar settings') }}</a></p>
            <p><a href="{{ url_for('profile.change_caller') }}" class="text-secondary">{{ _('Caller settings') }}</a></p>
            <p><a href="{{ url_for('profile.change_cpu_delay') }}" class="text-secondary">{{ _('Trainer delay settings') }}</a></p>   
            <p><a href="{{ url_for('profile.close_account') }}" class="text-secondary">{{ _('Close account') }}</a></p>                

        </div>
    </div>
</div>
{% endblock %}