lidarts/generic/forms.py
from flask_babelex import lazy_gettext
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class ChatmessageForm(FlaskForm):
    message = StringField('Message', validators=[DataRequired(), Length(max=500)])
    submit = SubmitField(lazy_gettext('Submit message'))


class UserSearchForm(FlaskForm):
    username = StringField(lazy_gettext('Search user'), validators=[DataRequired(), Length(max=30)])
    submit = SubmitField(lazy_gettext('Search'))

lidarts/generic/__init__.py
from flask import Blueprint

bp = Blueprint('generic', __name__)

from lidarts.generic import routes

lidarts/generic/routes.py
import time
from collections import defaultdict
from datetime import datetime, timedelta

from flask import jsonify, redirect, render_template, request, url_for, current_app
from flask_babelex import lazy_gettext
from flask_login import current_user, login_required
from sqlalchemy import desc, func, or_
from sqlalchemy.orm import aliased, load_only

from lidarts import db, socketio
from lidarts.game.forms import GameChatmessageForm
from lidarts.generic import bp
from lidarts.generic.forms import ChatmessageForm, UserSearchForm
from lidarts.models import (Chatmessage, CricketGame, Friendship,
                            FriendshipRequest, Game, GameBase, Notification,
                            Privatemessage, SocketConnections, User,
                            UserSettings, UserStatistic, WebcamSettings)
from lidarts.profile.utils import get_user_status
from lidarts.socket.utils import broadcast_online_players


@bp.route('/')
def index():
    # logged in users do not need the index page
    if current_user.is_authenticated:
        return redirect(url_for('generic.lobby'))
    return render_template('generic/index.html')


@bp.route('/about')
def about():
    return render_template('generic/about.html')


@bp.route('/contact')
def contact():
    return render_template('generic/contact.html')


@bp.route('/changelog')
def changelog():
    return render_template('generic/changelog.html')


@bp.route('/contribute')
def contribute():
    return render_template('generic/contribute.html')


@bp.route('/watch')
@bp.route('/watch/tournament/<tournament_hashid>')
def live_games_overview(tournament_hashid=None):
    live_games = Game.query.filter((Game.status == 'started'))

    if tournament_hashid:
        live_games = live_games.filter_by(tournament=tournament_hashid)

    live_games = live_games.order_by(Game.begin.desc()).limit(50).all()
    live_games_list = []
    players_in_list = []

    for game in live_games:
        if not game.player2 or game.player1 == game.player2:
            continue
        socketio.sleep(0)
        game_dict = game.__dict__
        player1_active = True
        player2_active = True
        player1_in_player_list = False
        player2_in_player_list = False

        if game.player1:
            player1 = User.query.get(game.player1)
            game_dict['player1_name'] = player1.username
            player1_active = player1.last_seen_ingame > datetime.utcnow() - timedelta(minutes=5)
            player1_in_player_list = game.player1 in players_in_list
        if game.player2:
            player2 = User.query.get(game.player2)
            # Local Guest needs his own 'name'
            game_dict['player2_name'] = player2.username if game.player1 != game.player2 else lazy_gettext('Local Guest')
            player2_active = player2.last_seen_ingame > datetime.utcnow() - timedelta(minutes=5)
            player2_in_player_list = game.player2 in players_in_list

        # only show game in watch tab if both players are recently ingame
        if player1_active and player2_active and not player1_in_player_list and not player2_in_player_list:
            live_games_list.append(game_dict)
            if game.player1:
                players_in_list.append(game.player1)
            if game.player2:
                players_in_list.append(game.player2)

        if len(live_games_list) >= 27:
            break

    return render_template('generic/watch.html', live_games=live_games_list, title=lazy_gettext('Live Games'))


@bp.route('/lobby', methods=['GET', 'POST'])
@login_required
def lobby():
    form = UserSearchForm()
    if form.validate_on_submit():
        return redirect(url_for('profile.overview', username=form.username.data).replace('%40', '@'))

    player_names = {}
    games_in_progress = Game.query.filter(((Game.player1 == current_user.id) | (Game.player2 == current_user.id)) &
                                          (Game.status.in_(['started', 'challenged']))).order_by(desc(Game.id)).all()
    cricket_games_in_progress = CricketGame.query.filter(((CricketGame.player1 == current_user.id) |
                                                          (CricketGame.player2 == current_user.id)) &
                                                         (CricketGame.status == 'started'))\
        .order_by(desc(CricketGame.id)).all()
    games_in_progress.extend(cricket_games_in_progress)
    for game in games_in_progress:
        if game.player1 and game.player1 not in player_names:
            player_names[game.player1] = User.query.with_entities(User.username) \
                .filter_by(id=game.player1).first_or_404()[0]
        if game.player2 and game.player2 not in player_names:
            player_names[game.player2] = User.query.with_entities(User.username) \
                .filter_by(id=game.player2).first_or_404()[0]

    # get own challenges
    own_challenges = GameBase.query.filter_by(status='challenged', player1=current_user.id).all()
    for game in own_challenges:
        opponent_name = User.query.with_entities(User.username) \
            .filter_by(id=game.player2).first()
        if opponent_name:
            player_names[game.player2] = opponent_name[0]
    own_challenges = [r.__dict__ for r in own_challenges]

    # get challenges
    challenges = GameBase.query.filter_by(status='challenged', player2=current_user.id).all()
    for game in challenges:
        player_names[game.player1] = User.query.with_entities(User.username) \
            .filter_by(id=game.player1).first_or_404()[0]
    challenges = [r.__dict__ for r in challenges]

    # get friend requests
    friend_requests = FriendshipRequest.query.filter_by(receiving_user_id=current_user.id).all()
    for friend_request in friend_requests:
        if friend_request.requesting_user_id not in player_names:
            player_names[friend_request.requesting_user_id] = User.query.with_entities(User.username) \
                .filter_by(id=friend_request.requesting_user_id).first_or_404()[0]

    # get online friends
    friend_query1 = Friendship.query.with_entities(Friendship.user2_id).filter_by(user1_id=current_user.id)
    friend_query2 = Friendship.query.with_entities(Friendship.user1_id).filter_by(user2_id=current_user.id)
    online_users = User.query.with_entities(User.id).filter(or_(User.is_online, User.last_seen > datetime.utcnow() - timedelta(minutes=1)))

    online_friend_list = friend_query1.union(friend_query2).intersect(online_users).all()
    online_friend_list = [r for r, in online_friend_list]

    for friend in online_friend_list:
        if friend not in player_names:
            player_names[friend] = (
                User.query.with_entities(User.username)
                .filter_by(id=friend)
                .first_or_404()[0]
            )

    player_names_sorted = {k: v for k, v in sorted(player_names.items(), key=lambda x: x[1])}
    online_friend_list.sort(key=lambda k: player_names_sorted[k])

    mobile_follower_mode = (
        WebcamSettings.query
        .with_entities(WebcamSettings.mobile_follower_mode)
        .filter_by(user=current_user.id)
        .first()
    )
    if mobile_follower_mode:
        mobile_follower_mode = mobile_follower_mode[0]
    else:
        mobile_follower_mode = False

    announcement = None
    if 'ANNOUNCEMENT_FILE' in current_app.config:
        try:
            with open(current_app.config['ANNOUNCEMENT_FILE']) as announcement_file:
                announcement = announcement_file.read()
        except FileNotFoundError:
            pass

    return render_template('generic/lobby.html', games_in_progress=games_in_progress, player_names=player_names,
                           friend_requests=friend_requests, online_friend_list=online_friend_list, form=form,
                           mobile_follower_mode=mobile_follower_mode,
                           challenges=challenges, own_challenges=own_challenges, announcement=announcement,
                           title=lazy_gettext('Lobby'))


@bp.route('/chat', methods=['GET', 'POST'])
@login_required
def chat():
    form = ChatmessageForm()
    messages = (
        Chatmessage.query
        .filter_by(tournament_hashid=None)
        .filter(Chatmessage.timestamp > (datetime.utcnow() - timedelta(hours=3)))
        .order_by(Chatmessage.id.desc())
        .limit(100)
        .from_self()
        .join(User).add_columns(User.username)
        .join(UserStatistic).add_columns(UserStatistic.average)
        .join(UserSettings).add_columns(UserSettings.country)        
        .all()
    )

    player1 = aliased(User)
    player2 = aliased(User)
    recent_results = (
        GameBase.query
        .options(load_only('id', 'player1', 'player2', 'status', 'end'))
        .filter_by(status='completed')
        .filter(GameBase.end != None)
        .filter(GameBase.player2 != None)
        .order_by(GameBase.end.desc())
        .limit(10)
        .from_self()
        .join(player1, GameBase.player1 == player1.id).add_columns(player1.username)
        .join(player2, GameBase.player2 == player2.id, isouter=True).add_columns(player2.username)
        .all()
    )

    for game, _, _ in recent_results:
        if game.bo_sets > 1:
            game.p1_final_score = game.p1_sets
            game.p2_final_score = game.p2_sets
        else:
            game.p1_final_score = game.p1_legs
            game.p2_final_score = game.p2_legs

    new_games = (
        GameBase.query
        .filter_by(status='started')
        .filter(GameBase.player1 != GameBase.player2)
        .order_by(GameBase.id.desc())
        .limit(10)
        .from_self()
        .join(player1, GameBase.player1 == player1.id).add_columns(player1.username)
        .join(player2, GameBase.player2 == player2.id, isouter=True).add_columns(player2.username)
        .all()
    )

    settings = UserSettings.query.filter_by(user=current_user.id).first()
    if not settings:
        settings = UserSettings(user=current_user.id)

lidarts/templates/generic/about.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card bg-light text-secondary bs-callout bs-callout-info">
            <div class="card-body">
                <h2 class="text-dark">{{ _('About lidarts.org') }}</h2>
                <hr>
                <p>{{ _('Lidarts is a') }} <a href="https://en.wikipedia.org/wiki/Free_and_open-source_software">{{ _('free/libre, open-source') }}</a> {{ _('online darts scoring website.') }}</p>
                <p>{{ _('Still being in a very early stage, the main goal for Lidarts\' future is to provide darts players an online service to play against real players and to help in their daily training.') }} {{ _('Many features are planned and wait for completion.') }}</p>
                <p>{{ _('The entire project is driven by volunteers. Everyone is invited to') }} <a href="{{ url_for('generic.contribute') }}">{{ _('contribute') }}</a>.</p>
                <p>{{ _('DartCall 2007 caller pack created by Horst Girtew.') }}</p>
                <p>{{ _('Sound effects obtained from') }} <a href="https://www.zapsplat.com">https://www.zapsplat.com</a></p>
            </div>
        </div>
    </div>
</div>




{% endblock %}

lidarts/templates/generic/changelog.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h2>Changelog</h2>
                <hr>
                <p>Lidarts is continuously being worked on. Below you can find the changelog for the latest releases.
                    To follow the development in detail visit our <a href="https://github.com/mischkadb/lidarts">GitHub repository</a>.</p>
                <hr>
                <h4>v0.5.0</h4>
                <p class="text-secondary">Not yet released</p>
                <p>
                <ul class="text-secondary">
                    <li>Added changeable user status indicator</li>
                    <li>Games can now be aborted</li>
                    <li>Challenges can now be withdrawn</li>
                    <li>Added connection indicator for both players in scorer </li>
                    <li>Added user avatars</li>
                    <li>Added basic player statistics in profile </li>
                    <li>Added basic private chat functions </li>
                    <li>Added notifications for new PMs and challenges </li>
                    <li>Added full match list in recent games</li>
                    <li>Added username changing </li>
                    <li>Password change and reset now enforce password policy </li>
                    <li>Backslash now removes last character in score input</li>
                    <li>Added computer matches to live games for now </li>
                    <li>Switched global chat time to local time zones</li>
                    <li>Declined challenges in recent games are now hidden</li>
                    <li>Fixed various small bugs </li>
                </ul>
                </p>
                <hr>
                <h4>v0.4.0</h4>
                <p class="text-secondary">6th of June 2018</p>
                <p>
                <ul class="text-secondary">
                    <li>Started adding public changelogs :-) (versions slowly become important)</li>
                    <li>Added public chat with online user name list</li>
                    <li>Added 'friend'-feature with friend online list</li>
                    <li>Improved online status handling</li>
                    <li>Added 'closest to bull' as starting player option</li>
                    <li>Added challenging other players via profile or name</li>
                    <li>Switched from CDNs to self-hosted javascript of various embedded scripts</li>
                    <li>Added some basic custom error pages</li>
                    <li>Added computer player with 9 different levels (~30 - ~90 average)</li>
                    <li>Added legal documents and a footer with most important links</li>
                    <li>Applied username and password policy</li>
                    <li>New and finished games now get displayed in public chat</li>
                    <li>Added watch tab which displays the 9 latest live games</li>
                    <li>Improved look of some pages and added various icons</li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</div>




{% endblock %}

lidarts/templates/generic/contact.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h2>{{ _('Contact') }}</h2>
                <hr>
                <p>{{ _('There are a few ways to contact us, more to come soon! No matter the reason, we try to reply as quickly as possible.') }}</p>
                <p>{{ _('At the moment we can provide you support in English or German.') }}</p>

                <p>Discord: <a href="https://discord.gg/devMXxf">lidarts Discord server</a></p>
                <p>GitHub: <a href="https://github.com/mischkadb/lidarts">{{ _('lidarts on GitHub') }}</a></p>
                <p>Email: <a href="mailto:contact@lidarts.org">contact@lidarts.org</a>
            </div>
        </div>
    </div>
</div>




{% endblock %}

lidarts/templates/generic/contribute.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h2>{{ _('Contribute to lidarts.org') }}</h2>
                <hr>
                <p>{{ _('Lidarts relies on volunteers to develop and maintain the project. There are several ways you can help out.') }}</p>

                <h4 class="mt-4">{{ _('Play and provide feedback') }}</h4>
                <hr>
                <p>{{ _('During development I try to test the features the best I can. But there will still be bugs that make it through to the live server.
                    If you encounter any bugs or problems during play or you have ideas or feedback to improve the site, please') }} <a href="{{ url_for('generic.contact') }}">{{ _('contact') }}</a> lidarts.</p>

                <h4 class="mt-4">{{ _('Tell your friends') }}</h4>
                <hr>
                <p>{{ _('Lidarts generates no money - it is free for everyone, we do not sell ads nor your data. The downside is the lack of a budget for marketing.
                    We rely on users to make Lidarts known to darts players. So tell your friends, invite them to play and spread the word!') }} </p>

                <h4 class="mt-4">{{ _('Translations') }}</h4>
                <hr>
                <p>{{ _('The main language on Lidarts is English. Translations exist in German, Danish and Dutch. If you are fluent in English and another language of your choice you can') }} <a href="{{ url_for('generic.help_translate') }}">{{ _('help translating') }}</a> {{ _('parts of Lidarts or the entire website for your community. ') }}</p>


                <h4 class="mt-4">{{ _('Graphics') }}</h4>
                <hr>
                <p>{{ _('The design of the website is not finished, but Lidarts mainly lacks some graphics to improve the look. Do you have the know-how to create graphics for Lidarts? If so,') }} <a href="{{ url_for('generic.contact') }}">{{ _('contact') }}</a> {{ _('us.') }}</p>

                <h4 class="mt-4">Design</h4>
                <hr>
                <p>{{ _('I am not a web designer and the website reflects that. At some point Lidarts will need a redesign and some help would be greatly appreciated.
                    You can help out with design ideas: Create a visual concept with Paint, Photoshop or whatever you like and') }} <a href="{{ url_for('generic.contact') }}">{{ _('send it to me.') }}</a>
                    {{ _('Or even better: you can work directly on the frontend and implement your ideas if you have some knowledge about HTML, CSS and JavaScript.') }}
                    {{ _('Interested?') }} <a href="{{ url_for('generic.contact') }}">{{ _('Contact Lidarts') }}</a> {{ _('or visit the') }} <a href="https://github.com/mischkadb/lidarts">GitHub repo</a>.</p>

                <h4 class="mt-4">{{ _('Programming') }}</h4>
                <hr>
                <p>{{ _('Of course you are more than welcome to join Lidarts and develop on the project. At the current stage I am all by myself and try to get the project contribution-ready.
                    If you are interested to get started take a look at the') }} <a href="https://github.com/mischkadb/lidarts">{{ _('GitHub repo') }}</a> {{ _('or') }} <a href="{{ url_for('generic.contact') }}">{{ _('contact me') }}</a>.</p>

                <h4 class="mt-4">{{ _('Donations') }}</h4>
                <hr>
                <p>{{ _('All features on Lidarts are free. However it requires money to pay for our servers and hosting. You can donate to the project to keep it free for others and smooth for everyone. Although you cannot buy access to any exclusive features, your contribution is acknowledged with a star next to your name on Lidarts for a month. Include your Lidarts username in your donation.') }}</a></p>
                <p>{{ _('Please note that Lidarts is not a registered non-profit organization by German law. All donations are taxed as the developer\'s income.') }}</p>
                <div class="text-center">
                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                        <input type="hidden" name="cmd" value="_s-xclick" />
                        <input type="hidden" name="hosted_button_id" value="RY4AAQVPN7KTS" />
                        <input type="image" src="https://www.paypalobjects.com/en_US/DK/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                        <img alt="" border="0" src="https://www.paypal.com/en_DE/i/scr/pixel.gif" width="1" height="1" />
                    </form>
                </div>
                



            </div>
        </div>
    </div>
</div>




{% endblock %}

lidarts/templates/generic/faq.html
{% extends "base.html" %}

{% block jumbotron %}
<div class="jumbotron">
    <div class="container">
        <h2>{{ _('Frequently Asked Questions' )}}</h2>
        <hr class="my-4">
        <h4 class="mt-2 anchor" id="What do I need to play">{{ _('What do I need to play?') }}</h4>
        <p>{{ _('To play you need a computer or a mobile device with a modern browser. Obviously you also need a darts setup.') }}</p>

        <h4 class="mt-4">{{ _('How do I find someone to play?') }}</h4>
        <p>{{ _('If you did not arrange a game with someone yet there are two easy options: Either join the chat and ask/look for a game there, or you can set up a public challenge when creating a game which will be visible to everyone else.') }}</p>

        <h4 class="mt-4">{{ _('How does \'closest to bull\' work?') }}</h4>
        <p>{{ _('In order to determine the starting player you throw three darts at bull. Enter and submit each dart score individually in order of throw. Darts outside of bull count as 0. The first better result over the other player begins. This means that for example 25-0-0 beats 0-50-50 as player 1 had a better result with an earlier dart.') }}</p>

        <h4 class="mt-4">{{ _('Can I play cricket or other variants?') }}</h4>
        <p>{{ _('Currently only X01 games are available. Cricket will be available soon. More dart games might follow.') }}</p>

        <h4 class="mt-4">{{ _('Can I use my webcam and see my opponent\'s throw?') }}</h4>
        <p>{{ _('Lidarts supports experimental webcam games over Jitsi Meet, a video conferencing service. You can also play without a webcam based on trust.') }}</p>

        <h4 class="mt-4">{{ _('How do I set up my webcam?') }}</h4>
        <p>{{ _('You need to connect your webcam (or smartphone with appropiate software) to your computer. Before your first game you have to agree to the current') }} <a href="{{ url_for('game.create', webcam=True) }}">{{ _('webcam service notice') }}</a>. {{ _('Create a game normally on the webcam page afterwards.') }}</p>

        <h4 class="mt-4">{{ _('Can I play steel and/or e-darts?') }}</h4>
        <p>{{ _('Both variants are welcome to play on Lidarts.') }}</p>

        <h4 class="mt-4">{{ _('Can I host and play in tournaments?') }}</h4>
        <p>{{ _('Currently tournament organizers can create a separate room with a tournament-specific chat, user list and result box. For brackets you need to use an external service. It will be possible to automate tournaments on Lidarts soon.') }}</p>

        <h4 class="mt-4">{{ _('How do I send private messages?') }}</h4>
        <p>{{ _('Open your inbox, enter the recipient\'s username in the box below and compose a new message.') }}</p>

        <h4 class="mt-4">{{ _('How do I add someone to my friend list?') }}</h4>
        <p>{{ _('You need to know your friend\'s username. Use the user search box in the lobby to find his profile. Click the friend request link there and wait for him to confirm.') }}</p>

        <h4 class="mt-4">{{ _('Where can I change my country flag / caller voice / username / password etc.') }}</h4>
        <p>{{ _('In your profile there is a settings button with lots of options. We highly recommend to look through the options before you play.') }}</p>

        <h4 class="mt-4">{{ _('My opponent throws so fast. What can I do?') }}</h4>
        <p>{{ _('There are usually two types of online players: Those who wait for their opponent to throw and those who don\'t. If you feel stressed you can set up an input block time upon game creating. We recommend between 5 and 10 seconds.') }}</p>

        <h4 class="mt-4">{{ _('What do the status colors mean?') }}</h4>
        <p>{{ _('Players can set most of these statuses manually. Green = online, yellow = Not available, purple = Looking for game, blue = currently playing, grey = offline.') }}</p>
   
        <h4 class="mt-4">{{ _('I found a bug / have a question or feature request / someone is cheating.') }}</h4>
        <p><a href="{{ url_for('generic.contact') }}">{{ _('Contact us.') }}</a></p>
    </div>
</div>
{% endblock %}

{% block app_content %}

{% endblock %}

lidarts/templates/generic/help_translate.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h2>{{ _('Help translating lidarts.org') }}</h2>
                <hr>
                <p>{{ _('Lidarts is currently available in four languages: English, German, Danish and Dutch. Translations to any language can be provided by the community.') }}</p>

                <h4 class="mt-4">{{ _('How to translate') }}</h4>
                <hr>
                <p>{{ _('If you speak any other language you can help translating Lidarts. You do not need any additional software.') }} {{ _('Visit our translation project on ') }}<a href="https://lidarts.crowdin.com/lidarts" target='_blank'>Crowdin</a>.</p>
                <p>{{ _('You can register a new account there or log in with various third party services. After logging in you can start translating texts to the language of your choice or improve existing translations.') }} {{ _('If your language is missing or you have any questions') }} <a href="{{ url_for('generic.contact') }}">{{ _('contact') }}</a> {{ _('us') }}.</p>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}

lidarts/templates/generic/inbox.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/jquery.powertip.min.css') }}" />
{% endblock %}

{% block app_content %}
<div class="row justify-content-center">
    <div class="col-sm-4">
        <div class="card bg-light text-dark">
            <div class="card-body" id="chat_partners" style="height: 642px; overflow-y: scroll;">
                {% for other_user in messages %}
                <div class="card chat-partner {% if loop.index == 1 %}chat-partner-active{% endif %}" id="chat_partner_{{ other_user }}">
                    <div class="card-body" style="padding: 2px 2px 2px 2px;">
                        <p><strong><h5><i class="fas fa-circle status-{{ status[other_user] }}" style="font-size: 15px;"></i>
                            {{ user_names[other_user] }}</h5></strong>
                        </p>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
        <p class="text-center mt-2">
            <input type="text" class="form-control" placeholder="{{ _('Enter name') }}" id="compose_message_name">
            <button class="btn btn-dark mt-1" id="compose_message">{{ _('Compose new message') }}</button>
        </p>
    </div>

    <div class="col-sm-8">
        <div class="card bg-light text-dark">
            <div class="card-body">
                <div class="card bg-light">
                    <div class="card-body" id="chatbox" style="height: 600px; overflow-y: scroll;">
                        <div id="chatbox-tabs">
                            {% for partner in messages %}
                            <div id="messages_tab_{{ partner }}" class="message-tab" {% if loop.index > 1 %}style="display: none"{% endif %}>
                                <h5 class="card-title">{{ _('Chat with') }} {{ user_names[partner] }}</h5>
                                {% for message in messages[partner] %}
                                <p>
                                    <strong>
                                        <a href="{{ url_for('profile.overview', username=user_names[message.sender]) | replace('%40', '@') }}" class="text-dark">{{ user_names[message.sender] }}</a>
                                    </strong> 
                                    <small class="text-secondary">{{ moment(message.timestamp).format('lll') }}</small><br>
                                    {{ message.message|safe }}
                                </p>
                                <hr>
                                {% endfor %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form id="message_input" method="POST" action="" class="mt-2">
            {{ form.hidden_tag() }}
            {{ form.message(class="form-control", autocomplete="off", maxlength="500") }}
            {{ form.submit(class="btn btn-dark mt-1") }}
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}
<meta id="validation_url" data-url="{{ url_for('generic.validate_chat_message') }}">
<meta id="compose_message_url" data-url="{{ url_for('generic.compose_message') }}">
<meta id="profile_url" data-url="{{ url_for('profile.overview') | replace('%40', '@') }}">
<meta id="game_url" data-url="{{ url_for('game.start') }}">
<meta id="user_id" data-id="{{ current_user.id }}">
<meta id="get_id_by_username_url" data-url="{{ url_for('generic.get_id_by_username') }}">

<script src="{{ url_for('static',filename='js/jquery.powertip.min.js', crossorigin='anonymous') }}" ></script>

<script type="text/javascript" src="{{ url_for('static',filename='js/private_messages_socket.js', version=config.VERSION) }}"></script>


{% endblock %}

lidarts/templates/generic/index.html
{% extends "base.html" %}

{% block jumbotron %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4 mb-4 "><img src="{{ url_for('static', filename='img/logo.png') }}" width="78" height="40" alt="lidarts logo" class=""> {{ _('Welcome to lidarts.org!') }}</h1> 
        <p class="lead">{{ _('lidarts.org is an') }} <a href="https://github.com/mischkadb/lidarts">{{ _('open-source') }}</a>, {{ _('forever free online darts website.') }} <span class="badge badge-danger">Beta</span></p>
        <hr class="my-4">
        <p class="mb-4">{{ _('Play darts against real opponents. With a webcam or without. Or train against the computer.') }} {{ _('No costs, no ads, no trackers.') }}</p>
        <p class="lead">
            <div class="btn-group btn-group-lg" role="group" aria-label="JumbotronButtons">
                <a href="{{ url_for('generic.about') }}"  class="btn btn-secondary" role="button"><i class="fas fa-info-circle"></i> {{ _('Learn more') }}</a></li>
                <a href="{{ url_for_security('register') }}" class="btn btn-info" role="button"><i class="fas fa-user-plus"></i> {{ _('Sign Up now') }}</a>
            </div>
        </p>
    </div>
</div>
{% endblock %}

{% block app_content %}

{% endblock %}