lidarts/game/forms.py
from flask_babelex import _, lazy_gettext
from flask_wtf import FlaskForm
from wtforms import IntegerField, SelectField, SubmitField, StringField, BooleanField
from wtforms.validators import DataRequired, InputRequired, NumberRange, ValidationError, Length

game_types = [('170', '170'), ('301', '301'), ('501', '501'), ('701', '701'), ('1001', '1001')]
opponents = [('local', lazy_gettext('Local')), ('online', 'Online'), ('computer', 'Computer')]
level = [(str(x), str(x)) for x in range(1, 10)]
starter = [('me', lazy_gettext('Me')), ('opponent', lazy_gettext('Opponent')),
           ('closest_to_bull', lazy_gettext('Closest to Bull'))]
bo_choice = [(str(x), str(x)) for x in range(1, 30)]
first_to_choice = [(str(x), str(x)) for x in range(1, 30)]
x_legs_choice = [(str(x), str(x)) for x in range(1, 50)]
in_choice = [('si', 'Straight In'), ('di', 'Double In')]
out_choice = [('do', 'Double Out'), ('so', 'Straight Out'), ('mo', 'Master Out')]


def impossible_numbers_check(form, field):
    impossible_numbers = [179, 178, 176, 175, 173, 172, 169]
    if field.data in impossible_numbers:
        raise ValidationError(lazy_gettext('Invalid number.'))


class ScoreForm(FlaskForm):
    score_value = IntegerField(lazy_gettext('Score'), validators=[InputRequired(),
                                                    NumberRange(min=0, max=180),
                                                    impossible_numbers_check])
    submit = SubmitField(lazy_gettext('Submit score'))


class CricketScoreForm(FlaskForm):
    score_value = IntegerField(lazy_gettext('Score'), validators=[InputRequired(),
                                                    NumberRange(min=0, max=180),
                                                    impossible_numbers_check])
    submit = SubmitField(lazy_gettext('Submit score'))


class CreateGameForm(FlaskForm):
    goal_mode = SelectField(lazy_gettext('Goal mode'), choices=[('best_of', 'Best of'), ('first_to', 'First to'), ('x_legs', 'X Legs')], validators=[DataRequired()])
    bo_sets = SelectField(lazy_gettext('Best of Sets'), choices=bo_choice, validators=[DataRequired()])
    bo_legs = SelectField(lazy_gettext('Best of Legs'), choices=bo_choice, validators=[DataRequired()])
    first_to_sets = SelectField(lazy_gettext('First to Sets'), choices=first_to_choice, validators=[DataRequired()])
    first_to_legs = SelectField(lazy_gettext('First to Legs'), choices=first_to_choice, validators=[DataRequired()])
    x_legs = SelectField(lazy_gettext('How many legs?'), choices=x_legs_choice, validators=[DataRequired()])
    two_clear_legs = BooleanField(lazy_gettext('Two Clear Legs'))
    two_clear_legs_wc_mode = BooleanField(lazy_gettext('World Championship Mode'))
    starter = SelectField(lazy_gettext('First to throw'), choices=starter, validators=[DataRequired()])
    opponent = SelectField(lazy_gettext('Opponent'), default='online', choices=opponents, validators=[DataRequired()])
    opponent_name = StringField(lazy_gettext('Opponent name'))
    level = SelectField(lazy_gettext('Level'), choices=level)
    public_challenge = BooleanField(lazy_gettext('Public challenge'))
    webcam = BooleanField(lazy_gettext('Webcam game'))
    score_input_delay = IntegerField(lazy_gettext('Score input block'), default=0, validators=[NumberRange(min=0, max=15)])
    save_preset = BooleanField(lazy_gettext('Save settings'))
    tournament = SelectField(lazy_gettext('Tournament'), choices=[])
    submit = SubmitField(lazy_gettext('Start game'))


class CreateX01GameForm(CreateGameForm):
    type = SelectField(lazy_gettext('Game type'), choices=game_types, validators=[DataRequired()])
    in_mode = SelectField(lazy_gettext('Mode In'), choices=in_choice, validators=[DataRequired()])
    out_mode = SelectField(lazy_gettext('Mode Out'), choices=out_choice, validators=[DataRequired()])


class CreateCricketGameForm(CreateGameForm):
    pass


class GameChatmessageForm(FlaskForm):
    message = StringField('Message', validators=[DataRequired(), Length(max=500)])
    submit = SubmitField(lazy_gettext('Submit message'))


class WebcamConsentForm(FlaskForm):
    webcam_consent = BooleanField(lazy_gettext('I have read the text above, understand the limitations and have a webcam setup to play.'), validators=[DataRequired()], default=False)
    stream_consent = BooleanField(lazy_gettext('(Optional) I allow my opponents to stream and record our game including my webcam video and audio.'), default=False)
    submit = SubmitField(lazy_gettext('Confirm'))

lidarts/game/__init__.py
from flask import Blueprint

bp = Blueprint('game', __name__, url_prefix='/game')

from lidarts.game import routes

lidarts/game/routes.py
from flask import render_template, redirect, url_for, jsonify, request, flash, current_app
from flask.globals import current_app
from flask_babelex import lazy_gettext, gettext
from lidarts.game import bp
from lidarts.game.forms import CreateCricketGameForm, CreateX01GameForm, ScoreForm, GameChatmessageForm, WebcamConsentForm
from lidarts.models import CricketGame, Game, GameBase, User, Notification, ChatmessageIngame, X01Presetting, UserSettings, Tournament, WebcamSettings
from lidarts import db
from lidarts.socket.public_challenge_handler import broadcast_public_challenges
from lidarts.socket.utils import broadcast_game_aborted, broadcast_new_game, send_notification
from lidarts.game.consts import ACTIVE_GAME_LIMIT, GAME_CREATION_TIME_COOLDOWN_SECONDS
from lidarts.game.cricket.prepare_form import prepare_cricket_form
from lidarts.game.cricket.save_preset import save_cricket_preset
from lidarts.game.X01.prepare_form import prepare_x01_form
from lidarts.game.X01.save_preset import save_x01_preset
from lidarts.game.utils import get_name_by_id, collect_statistics, get_player_names, cricket_leg_default
from lidarts.socket.X01_game_handler import start_game
from flask_login import current_user, login_required
from datetime import datetime, timedelta
import json
import secrets
from sqlalchemy import func




@bp.route('/create', methods=['GET', 'POST'])
@bp.route('/create/<mode>', methods=['GET', 'POST'])
@bp.route('/create/<mode>/<opponent_name>', methods=['GET', 'POST'])
@bp.route('/create/tournament/<tournament_hashid>', methods=['GET', 'POST'])
@bp.route('/create/tournament/<tournament_hashid>/<opponent_name>', methods=['GET', 'POST'])
@login_required
def create(mode='x01', opponent_name=None, tournament_hashid=None):
    if mode == 'x01':
        form = prepare_x01_form(opponent_name, tournament_hashid)
    else:
        form = prepare_cricket_form(opponent_name, tournament_hashid)        

    webcam_query = WebcamSettings.query.filter_by(user=current_user.id).first()
    if not webcam_query or not webcam_query.activated:
        if form.webcam.data:
            return redirect(url_for('game.webcam_consent'))
        form.webcam.render_kw = {'disabled': 'disabled'}

    if form.validate_on_submit():
        player1 = current_user.id if current_user.is_authenticated else None

        # check if player1 created too many games to prevent spamming    
        active_games = GameBase.query.filter_by(player1=player1).filter(GameBase.status.in_(['started', 'challenged'])).count()
        if active_games >= ACTIVE_GAME_LIMIT:
            flash(gettext('You have too many active games. Please finish some games before creating new ones.'), 'danger')
            return render_template('game/create_game.html', form=form, opponent_name=opponent_name,
                                   title=lazy_gettext('Create Game'))
        
        # check if player1 created a game too recently to prevent spamming
        last_game = GameBase.query.filter_by(player1=player1).order_by(GameBase.begin.desc()).first()
        if last_game and last_game.begin > datetime.utcnow() - timedelta(seconds=GAME_CREATION_TIME_COOLDOWN_SECONDS):
            flash(gettext('You have created a game too recently. Please wait a bit before creating a new one.'), 'danger')
            return render_template('game/create_game.html', form=form, opponent_name=opponent_name,
                                   title=lazy_gettext('Create Game'))

        if player1 and form.opponent.data == 'local':
            player2 = current_user.id
            status = 'started'
        elif player1 and form.opponent.data == 'online':
            if form.opponent_name.data:
                if form.public_challenge.data:
                    # Public challenge flag and player name specified is not allowed
                    flash(gettext('Public challenges must be created without an opponent name.'), 'danger')
                    return render_template('game/create_game.html', form=form, opponent_name=opponent_name,
                           title=lazy_gettext('Create Game'))
                player2 = (
                    User.query
                    .with_entities(User.id)
                    .filter(func.lower(User.username) == func.lower(form.opponent_name.data))
                    .first_or_404()
                )

                player2_settings = UserSettings.query.filter_by(user=player2.id).first()
                if player2_settings and not player2_settings.allow_challenges:
                    # player 2 does not allow challenge requests
                    flash(gettext('Player does not allow challenges'), 'danger')
                    return render_template('game/create_game.html', form=form, opponent_name=opponent_name,
                           title=lazy_gettext('Create Game'))

                message = gettext('New challenge')
                notification = Notification(user=player2, message=message, author=current_user.username,
                                            type='challenge')
                db.session.add(notification)
                send_notification(form.opponent_name.data, message, current_user.username, 'challenge', webcam=form.webcam.data)
            else:
                player2 = None
            status = 'challenged'
        else:
            # computer as opponent
            player2 = None
            status = 'started'

        if form.webcam.data:
            if player2:
                webcam_player2 = WebcamSettings.query.filter_by(user=player2).first()
                if not webcam_player2 or not webcam_player2.activated:
                    flash(gettext('Player 2 does not have webcam games enabled.'), 'danger')
                    return render_template('game/create_game.html', form=form, opponent_name=opponent_name,
                            title=lazy_gettext('Create Game'))
            else:
                webcam_player2 = None
            jitsi_hashid = secrets.token_urlsafe(8)[:8]
            webcam_player1 = WebcamSettings.query.filter_by(user=player1).first()
            jitsi_public_server = webcam_player1.jitsi_public_server or (webcam_player2 and webcam_player2.jitsi_public_server)
        else:
            jitsi_hashid = None
            jitsi_public_server = False

        tournament = form.tournament.data if form.tournament.data != '-' else None

        try:
            player2_id = player2.id
        except AttributeError:
            player2_id = player2

        if form.two_clear_legs_wc_mode.data:
            form.two_clear_legs.data = False

        # Convert "first to" to "best of" for consistency
        if form.goal_mode.data == 'first_to':
            form.bo_sets.data = (2 * int(form.first_to_sets.data)) - 1
            form.bo_legs.data = (2 * int(form.first_to_legs.data)) - 1
        elif form.goal_mode.data == 'x_legs':
            form.bo_sets.data = 1
            form.bo_legs.data = 1

        if mode == 'x01':
            match_json = json.dumps({1: {1: {1: {'scores': [], 'double_missed': []},
                                         2: {'scores': [], 'double_missed': []}}}})
            game = Game(
                player1=player1, player2=player2_id, type=form.type.data,
                variant='x01',
                bo_sets=form.bo_sets.data, bo_legs=form.bo_legs.data,
                fixed_legs=form.goal_mode.data == 'x_legs', fixed_legs_amount=form.x_legs.data,
                two_clear_legs=form.two_clear_legs.data,
                two_clear_legs_wc_mode=form.two_clear_legs_wc_mode.data,
                p1_sets=0, p2_sets=0, p1_legs=0, p2_legs=0,
                p1_score=int(form.type.data), p2_score=int(form.type.data),
                in_mode=form.in_mode.data, out_mode=form.out_mode.data,
                begin=datetime.utcnow(), match_json=match_json,
                status=status, opponent_type=form.opponent.data,
                public_challenge=form.public_challenge.data,
                tournament=tournament, 
                score_input_delay=form.score_input_delay.data,
                webcam=form.webcam.data, jitsi_hashid=jitsi_hashid,
                jitsi_public_server=jitsi_public_server,
                )
        elif mode == 'cricket':
            match_json = json.dumps(
                {
                    1: {
                        1: cricket_leg_default.copy(),
                    },
                },
            )
            game = CricketGame(
                player1=player1, player2=player2_id, variant='cricket',
                bo_sets=form.bo_sets.data, bo_legs=form.bo_legs.data,
                fixed_legs=form.goal_mode.data == 'x_legs', fixed_legs_amount=form.x_legs.data,
                two_clear_legs=form.two_clear_legs.data,
                two_clear_legs_wc_mode=form.two_clear_legs_wc_mode.data,
                p1_sets=0, p2_sets=0, p1_legs=0, p2_legs=0,
                p1_score=0, p2_score=0,
                begin=datetime.utcnow(), match_json=match_json,
                status=status, opponent_type=form.opponent.data,
                public_challenge=form.public_challenge.data,
                tournament=tournament, 
                score_input_delay=form.score_input_delay.data,
                webcam=form.webcam.data, jitsi_hashid=jitsi_hashid,
                jitsi_public_server=jitsi_public_server,
                )
        else:
            pass

        # Preset saving
        if form.save_preset.data:
            if mode == 'x01':
                save_x01_preset(form)
            elif mode == 'cricket':
                save_cricket_preset(form)
            else:
                pass

        if game.opponent_type.startswith('computer'):
            game.opponent_type += form.level.data

        game.p1_next_turn = form.starter.data == 'me'
        if form.starter.data == 'closest_to_bull':
            game.p1_next_turn = True
            closest_to_bull_json = json.dumps({1: [], 2: []})

lidarts/templates/game/X01_statistics.html
{% extends "base.html" %}

{% block app_content %}
{% set playerWon = 1 %}
{% if 'to_finish' in leg_data_json['2'] %}
{%     set playerWon = 2 %}
{% endif %}

<div class="row justify-content-center mb-2">
    <div class="col">
        <div class="card bg-light">
            <div class="card-body">
                <div class="row justify-content-center align-items-center mb-2">
                    <div class="col-6 text-center text-light">
                        <div class="card bg-dark">
                            <div class="card-body player_name_card"><h1>{{ playerNames[0] }}</h1></div>
                            <div class="card-footer
                            {% if playerWon == 1 %}bg-success border-success
                            {% else %}bg-danger border-danger{% endif %}"></div>
                        </div>
                    </div>

                    <div class="col-6 text-center text-light">
                        <div class="card bg-dark">
                            <div class="card-body player_name_card"><h1>{{ playerNames[1] }}</h1></div>
                            <div class="card-footer
                            {% if playerWon == 2 %}bg-success border-success
                            {% else %}bg-danger border-danger{% endif %}"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row justify-content-center mb-2">
    <div class="col-xl-12">
        <div class="card bg-light">
            <div class="card-body">
                <!-- Row with starting scores -->
                <div class="row align-items-center no-gutters mb-2">
                    <div class="col-5 col-sm-2 offset-sm-3 text-center">
                        <h1>{{ starting_score }}</h1>
                    </div>
                    <div class="col-5 col-sm-2 offset-2 text-center">
                        <h1>{{ starting_score }}</h1>
                    </div>
                </div>
                {%  set countScoresPlayerOne = leg_data_json['1']['scores']|length %}
                {%  set countScoresPlayerTwo = leg_data_json['2']['scores']|length %}
                {%  for entry in range([countScoresPlayerOne, countScoresPlayerTwo]|max) %}
                <div class="row align-items-center no-gutters mb-2">
                    <div class="col-1 text-center d-none d-sm-block"><!-- show on bigger screen -->
                        <h2 class="darts_on_doubles_count">{{ leg_data_json['1']['double_attempts'][entry] }}</h2>
                    </div>
                    <div class="col-2 text-center d-none d-sm-block"><!-- show on bigger screen -->
                        <h1>{{ leg_data_json['1']['scores'][entry] }}</h1>
                    </div>
                    <div class="col-5 text-center d-sm-none"><!-- show on small screen -->
                        <h1>{{ leg_data_json['1']['remaining_scores'][entry] }}</h1>
                    </div>
                    <div class="col-2 text-center d-none d-sm-block"><!-- show on bigger screen -->
                        <h1>{{ leg_data_json['1']['remaining_scores'][entry] }}</h1>
                    </div>
                    <div class="col-2 text-center" >
                        <h1><b>{{ (entry + 1) * 3 }}</b></h1>
                    </div>
                    <div class="col-2 text-center d-none d-sm-block"><!-- show on bigger screen -->
                        <h1>{{ leg_data_json['2']['remaining_scores'][entry] }}</h1>
                    </div>
                    <div class="col-5 text-center d-sm-none"><!-- show on small screen -->
                        <h1>{{ leg_data_json['2']['remaining_scores'][entry] }}</h1>
                    </div>
                    <div class="col-2 text-center d-none d-sm-block">
                        <h1>{{ leg_data_json['2']['scores'][entry] }}</h1>
                    </div>
                    <div class="col-1 text-center d-none d-sm-block">
                            <h2 class="darts_on_doubles_count">{{ leg_data_json['2']['double_attempts'][entry] }}</h2>
                    </div>
                </div>
                {% endfor %}
                <!--
                <div class="row justify-content-center align-items-center mb-2 text-center text-secondary">
                    <div class="col-sm-3 offset-sm-1">
                        <div class="card bg-light text-dark">
                            <div class="card-body player_name_card">
                                <p>aAvg.</p>
                                <p>First 9 Avg.</p>
                                <p>Doubles</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="card bg-light">
                        <div class="card-body player_name_card">
                            <p>Avg.</p>
                            <p>First 9 Avg.</p>
                            <p>Doubles</p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="card bg-light text-dark">
                        <div class="card-body player_name_card">
                            <p>test</p>
                        </div>
                    </div>
                </div>
                -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

lidarts/templates/game/create_X01.html
{% extends "base.html" %}

{% block app_content %}
<div class="row justify-content-center mb-2">
    <div class="col-12 col-md-6 text-center">
        <div class="card">
            <div class="card-body">
                <div class="row justify-content-center">
                    <h1>{{ _('Create Game') }}</h1>
                </div>

                <hr>

                <div class="row justify-content-center text-secondary">
                    <div class="col-6 text-right align-self-center ">
                        {{ _('Game Mode') }}:
                    </div>
                    <div class="col-6 align-self-center text-left">
                        <div class="dropdown show">
                            <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                X01
                            </a>
                            <div class="dropdown-menu" aria-labelledby="gameModeDropdown">
                                <a class="dropdown-item" href="{{ url_for('game.create') }}/x01">X01</a>
                                <a class="dropdown-item" href="#">-</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="post" class="form-horizontal">
    {{ form.hidden_tag() }}

    <div class="row justify-content-center text-secondary">
        <div class="col-lg-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <p>{{ form.type.label(class="control-label") }}:
                        {{ form.type(class="form-control custom-select") }}</p>

                    <p>{{ form.opponent.label(class="col-form-label") }}:
                        {{ form.opponent(class="custom-select", onchange="computercheck(this);") }}
                    </p>

                    <p {% if form.opponent.data != 'computer' %}style="display: none;"{% endif %} id="levels">{{ form.level.label(class="col-form-label") }}:
                        {{ form.level(class="custom-select") }}
                    </p>

                    <p {% if form.opponent.data != 'online' %}style="display: none;"{% endif %}id="opponent_name">{{ form.opponent_name.label(class="col-form-label") }}:
                        {{ form.opponent_name(class="form-control") }}
                    </p>

                    <p>
                        <div class="custom-control custom-checkbox" {% if form.opponent.data != 'online' %}style="display: none;"{% endif %} id="public_challenge_div">
                        {{ form.public_challenge(class="custom-control-input") }}
                        {{ form.public_challenge.label(class="custom-control-label") }}
                        </div>
                    </p>

                    <p {% if form.opponent.data != 'online' %}style="display: none;"{% endif %} id="tournaments">
                        {{ form.tournament.label(class="col-form-label") }}:
                        {{ form.tournament(class="custom-select") }}
                    </p>


                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <p>{{ form.bo_sets.label(class="col-form-label") }}:
                        {{ form.bo_sets(class="custom-select") }}</p>

                    <p>{{ form.bo_legs.label(class="col-form-label") }}:
                        {{ form.bo_legs(class="custom-select") }}</p>

                    <p><div class="custom-control custom-checkbox">
                        {{ form.two_clear_legs(class="custom-control-input") }}
                        {{ form.two_clear_legs.label(class="custom-control-label") }}
                        </div>
                    </p>

                    <p><div class="custom-control custom-checkbox">
                        {{ form.webcam(class="custom-control-input") }}
                        {{ form.webcam.label(class="custom-control-label") }}
                        </div>
                        {% if form.webcam.render_kw and 'disabled' in form.webcam.render_kw %}
                        <small><a href="{{ url_for('game.webcam_consent') }}">{{ _('You have to activate webcam games first.') }}</a></small>
                        {% endif %}
                    </p>

                    <p><div class="custom-control custom-checkbox">
                        {{ form.save_preset(class="custom-control-input") }}
                        {{ form.save_preset.label(class="custom-control-label") }}
                        </div>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-sm-1">
            <div class="card">
                <div class="card-body">
                    <p>{{ form.starter.label(class="col-form-label") }}:
                        {{ form.starter(class="custom-select") }}</p>

                    <p>{{ form.in_mode.label(class="col-form-label") }}:
                        {{ form.in_mode(class="custom-select") }}</p>

                    <p>{{ form.out_mode.label(class="col-form-label") }}:
                        {{ form.out_mode(class="custom-select") }}</p>


                    <p>
                        {{ form.score_input_delay.label(class="col-form-label") }}:
                        {{ form.score_input_delay(class="custom-select") }}
                        <small>{{ _('Blocks score input after new score. In seconds.') }}</small>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6"></div>
    </div>
    <div class="row justify-content-center text-center">
        <div class="col-sm-3">{{ form.submit(class="btn btn-lg btn-info") }}</div>
    </div>
</form>


{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function computercheck(that) {
        if (that.value == 'computer') {
            document.getElementById("levels").style.display = "block";
            document.getElementById("public_challenge_div").style.display = "none";
            document.getElementById("opponent_name").style.display = "none";
            document.getElementById("tournaments").style.display = "none";          
        } else if (that.value == 'online') {
            document.getElementById("levels").style.display = "none";
            document.getElementById("public_challenge_div").style.display = "block";
            document.getElementById("opponent_name").style.display = "block";    
            document.getElementById("tournaments").style.display = "block";        
        } else {
            document.getElementById("levels").style.display = "none";
            document.getElementById("public_challenge_div").style.display = "none";
            document.getElementById("opponent_name").style.display = "none";
            document.getElementById("tournaments").style.display = "none";
        }
    }
</script>
{% endblock %}

lidarts/templates/game/game_navbar.html
<nav class="navbar navbar-expand-xl sticky-top navbar-dark bg-dark">

    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <div class="row mb-2 text-secondary">
                <a href="{{ url_for('generic.index') }}" class="text-secondary"> {{ _('Leave game') }}</a>
                {% if current_user.id == game.player1 or current_user.id == game.player2 %}
                | <div id="abort-game" class="div-link">{{ _('Abort game') }}</div>
                | <div id="hide-keypad" class="div-link">{{ _('Toggle Keypad visibility') }}</div>
                | <div id="change-keypad" class="div-link">{{ _('Change keypad position') }}</div>
                {% endif %}
                | <div id="hide-statistics" class="div-link">{{ _('Toggle statistics') }}</div>
                {% if stream %}
                | <a href="{{ url_for('game.start', hashid=game.hashid) }}" class="text-secondary">{{ _('Normal theme')
                    }}</a>
                {% else %}
                | <a href="{{ url_for('game.start', hashid=game.hashid, theme='stream') }}" class="text-secondary">{{
                    _('Streamoverlay') }}</a>
                {% endif %}
                | <div id="mute" style="{% if caller_muted %}display: none{% endif %}" class="div-link">
                    {{ _('Mute caller') }}
                </div>
                <div id="unmute" style="{% if not caller_muted %}display: none{% endif %}" class="div-link">
                    {{ _('Unmute caller') }}</div>
                <div id="appleActivateSound" class="div-link" style="display: none">| {{ _('Activate Sound (Apple)') }}
                </div>
                {% if game.webcam and current_user.is_authenticated and (game.player1 == current_user.id or game.player2
                == current_user.id) and current_user.webcam_settings and
                current_user.webcam_settings.mobile_follower_mode %}
                | <div id="summon-webcam" class="div-link">{{ _('Summon webcam') }}</div>
                {% endif %}
                {% if game.webcam and not stream_consent %}
                | <span class="fa-stack fa-2x" style="font-size: 0.7em"
                    title="{{ _('At least one player does not allow streaming.') }}">
                    <i class="fas fa-video fa-stack-1x text-white"></i>
                    <i class="fas fa-ban fa-stack-2x text-danger"></i>
                </span>
                {% endif %}

            </div>
        </div>
    </div>
</nav>

lidarts/templates/game/leg_set_count_small.html
<div class="row justify-content-center align-items-start text-center mt-2">
    <!-- LEG AND SET COUNT SMALL -->
    <div class="col-md-4 offset-md-1 col-6 d-lg-none">
        <div class="card bg-info text-light">
            <div class="card-body leg-set-card-small" style="padding-top: 0px; padding-bottom: 0px">
                <div class="row justify-content-center">
                    {% if game.bo_sets > 1 %}<div class="col-6">Sets: <strong class="p1_sets">{{ game.p1_sets }}</strong></div>{% endif %}
                    <div class="col-6">Legs: <strong class="p1_legs">{{ game.p1_legs }}</strong></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 offset-md-2 col-6 d-lg-none">
        <div class="card bg-info text-light">
            <div class="card-body leg-set-card-small" style="padding-top: 0px; padding-bottom: 0px">
                <div class="row justify-content-center">
                    {% if game.bo_sets > 1 %}<div class="col-6">Sets: <strong class="p2_sets">{{ game.p2_sets }}</strong></div>{% endif %}
                    <div class="col-6">Legs: <strong class="p2_legs">{{ game.p2_legs }}</strong></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-1"></div>
</div>