lidarts/legal/__init__.py
# -*- coding: utf-8 -*-

"""Legal Blueprint initialization.

Includes disclaimer, privacy notice, imprint, T&C etc.
"""

from flask import Blueprint


bp = Blueprint('legal', __name__)

from lidarts.legal import routes  # noqa F401

lidarts/legal/routes.py
# -*- coding: utf-8 -*-

"""Routes for legal stuff.

Includes disclaimer, privacy notice, imprint, T&C etc.
"""

from flask import render_template

from lidarts.legal import bp


@bp.route('/legal_notice')
def legal_notice():
    """Legal notice (English).

    Returns:
        Legal notice template
    """
    return render_template('legal/legal_notice.html')


@bp.route('/disclaimer')
def disclaimer():
    """Disclaimer (English).

    Returns:
        Disclaimer template
    """
    return render_template('legal/disclaimer.html')


@bp.route('/privacy')
def privacy():
    """Privacy notice (English).

    Returns:
        Privacy template
    """
    return render_template('legal/privacy.html')


@bp.route('/legal_notice/german')
def legal_notice_german():
    """Legal notice (German).

    Returns:
        Legal notice template
    """
    return render_template('legal/german/legal_notice.html')


@bp.route('/disclaimer/german')
def disclaimer_german():
    """Disclaimer (German).

    Returns:
        Disclaimer template
    """
    return render_template('legal/german/disclaimer.html')


@bp.route('/privacy/german')
def privacy_german():
    """Privacy notice (German).

    Returns:
        Privacy template
    """
    return render_template('legal/german/privacy.html')


@bp.route('/terms_and_conditions')
def terms_and_conditions():
    """Terms and Conditions (English).

    Returns:
        T&C template
    """
    return render_template('legal/terms_and_conditions.html')

lidarts/templates/legal/disclaimer.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h3><a href="{{ url_for('legal.disclaimer_german') }}">Deutsche Version / German version</a></h3>
                <h2 style="margin-bottom: 0.5rem;">Liability for Contents</h2>
                <p>As service providers, we are liable for own contents of these websites according to Sec. 7, paragraph 1 German Telemedia Act (TMG). However, according to Sec. 8 to 10 German Telemedia Act (TMG), service providers are not obligated to  permanently monitor submitted or stored information or to search for evidences that indicate illegal activities.</p>
                <p>Legal obligations to removing information or to blocking the use of information remain unchallenged. In this case, liability is only possible at the time of knowledge about a specific violation of law. Illegal contents will be removed immediately at the time we get knowledge of them.</p>
                <h2 style="margin-bottom: 0.5rem;">Liability for Links</h2>
                <p>Our offer includes links to external third party websites. We have no influence on the contents of those websites, therefore we cannot guarantee for those contents. Providers or administrators of linked websites are always responsible for their own contents.</p>
                <p>The linked websites had been checked for possible violations of law at the time of the establishment of the link. Illegal contents were not detected at the time of the linking. A permanent monitoring of the contents of linked websites cannot be imposed without reasonable indications that there has been a violation of law. Illegal links will be removed immediately at the time we get knowledge of them.</p>
                <h2 style="margin-bottom: 0.5rem;">Copyright</h2>
                <p>Contents and compilations published on these websites by the providers are subject to German copyright laws. Reproduction, editing, distribution as well as the use of any kind outside the scope of the copyright law require a written permission of the author or originator. Downloads and copies of these websites are permitted for private use only.<br />
                    The commercial use of our contents without permission of the originator is prohibited.</p>
                <p>Copyright laws of third parties are respected as long as the contents on these websites do not originate from the provider. Contributions of third parties on this site are indicated as such. However, if you notice any violations of copyright law, please inform us. Such contents will be removed immediately.</p>

            </div>
        </div>
    </div>
</div>




{% endblock %}

lidarts/templates/legal/legal_notice.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h3><a href="{{ url_for('legal.legal_notice_german') }}">Deutsche Version / German version</a></h3>
                <h1 style="margin-bottom: 0.5rem;">Site Notice</h1>

                <h2 style="margin-bottom: 0.5rem;">Information provided according to Sec. 5 German Telemedia Act (TMG):</h2>
                <p>Michael Engel<br />
                    Zscheilaer Strasse 38<br />
                    01662 Meissen<br />
                    Germany</p>

                <h2 style="margin-bottom: 0.5rem;">Contact:</h2>
                <p>Telephone: + 49 1522 3612577<br />
                    Email: contact@lidarts.org</p>

                <h3 style="margin-bottom: 0.5rem;">Liability for Contents</h3>
                <p>As service providers, we are liable for own contents of these websites according to Sec. 7, paragraph 1 German Telemedia Act (TMG). However, according to Sec. 8 to 10 German Telemedia Act (TMG), service providers are not obligated to permanently monitor submitted or stored information or to search for evidences that indicate illegal activities.</p>
                <p>Legal obligations to removing information or to blocking the use of information remain unchallenged. In this case, liability is only possible at the time of knowledge about a specific violation of law. Illegal contents will be removed immediately at the time we get knowledge of them.</p>
                <h3 style="margin-bottom: 0.5rem;">Liability for Links</h3>
                <p>Our offer includes links to external third party websites. We have no influence on the contents of those websites, therefore we cannot guarantee for those contents. Providers or administrators of linked websites are always responsible for their own contents.</p>
                <p>The linked websites had been checked for possible violations of law at the time of the establishment of the link. Illegal contents were not detected at the time of the linking. A permanent monitoring of the contents of linked websites cannot be imposed without reasonable indications that there has been a violation of law. Illegal links will be removed immediately at the time we get knowledge of them.</p>
                <h3 style="margin-bottom: 0.5rem;">Copyright</h3>
                <p>Contents and compilations published on these websites by the providers are subject to German copyright laws. Reproduction, editing, distribution as well as the use of any kind outside the scope of the copyright law require a written permission of the author or originator. Downloads and copies of these websites are permitted for private use only.<br /> The commercial use of our contents without permission of the originator is prohibited.</p>
                <p>Copyright laws of third parties are respected as long as the contents on these websites do not originate from the provider. Contributions of third parties on this site are indicated as such. However, if you notice any violations of copyright law, please inform us. Such contents will be removed immediately.</p>
                <p> </p>


            </div>
        </div>
    </div>
</div>




{% endblock %}

lidarts/templates/legal/terms_and_conditions.html
{% extends "base.html" %}

{% block app_content %}


<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card bg-light text-dark bs-callout bs-callout-info">
            <div class="card-body">
                <h2>Terms and Conditions</h2>
                <hr>
                <h3 class="mt-3">Welcome to Lidarts!</h3>
                <p>This page explains our terms and conditions. When you use Lidarts, you’re agreeing to all the rules on this page.
                    Some of them need to be expressed in legal language, but we’ve done our best to offer you clear and
                    simple explanations of what everything means.</p>

                <p>By using this website (the “Site”) and services (together with the Site, the “Services”) offered by
                    Lidarts.org (together with our subsidiaries, affiliates, representatives, and directors –
                    collectively “Lidarts”, “we”, or “us”) you’re agreeing to these legally binding rules (the “Terms”).
                    You’re also agreeing to our <a href="{{ url_for('legal.privacy') }}">Privacy Policy</a>, and agreeing
                    to follow any other rules on the Site, like our Community Guidelines (included below).</p>

                <p>We may change these terms from time to time. If we do, we’ll let you know about any significant or
                    material changes, by notifying you on the Site. New versions of the terms will never apply retroactively
                    – we’ll tell you the exact date they go into effect. If you continue using Lidarts after a change,
                    that means you accept the new terms.</p>

                <h3 class="mt-4">Introduction</h3>
                <hr>
                <p>Lidarts strives to become a full-fledged online darts scoring website to help our users play and train
                    darts in an enjoyable, interactive way.</p>
                <p>As an open-source project with no monetary income, we rely on work by volunteers to keep the service up
                    and improve it further. We always have a friendly ear for feedback and suggestions to improve your
                    experience on our site, so don't hesitate to <a href="{{ url_for('generic.contact') }}">contact us.</a>
                </p>

                <h3 class="mt-4">About Creating an Account</h3>
                <hr>
                <p>To sign up for a Lidarts account, you need to be 16 or over. If you’re under 16, you can only use
                    Lidarts only with parental-guardian supervision and consent. You’re responsible for your account
                    and all the activity on it.</p>

                <p>You can browse Lidarts without registering for an account. But to use some of Lidarts’s functions,
                    you’ll need to register, choose a username, and set a password. When you do that, the information
                    you give us has to be accurate and complete. Don’t impersonate anyone else or choose names that are
                    offensive or that violate anyone’s rights. If you don’t follow these rules, we may cancel your account.</p>

                <p>When these terms discuss “Users” or a “User”, we’ll be referring to both registered and unregistered users,
                    unless it relates to features, information or data an unregistered User does not or cannot have access to.</p>

                <h3 class="mt-4">License and Usage</h3>
                <hr>
                <p>Lidarts is a free/libre open-source software project licensed under the GNU Affero General Public License. More information on this
                    can be found in our <a href="https://github.com/mischkadb/lidarts/blob/master/LICENSE">License file</a>.
                    Registered Users can use all of Lidarts' features for their own personal purposes. Lidarts reserves the right
                    to decide what kind of use of the Services is appriopriate.
                </p>

                <h3 class="mt-4">Account termination</h3>
                <hr>
                <p>You can delete your account at any time. This will permanently erase your account and all data associated
                    with it. However we may retain certain information as required by law or for our legitimate business purposes.
                    Account termination can only be requested by <a href="mailto:contact@lidarts.org">contacting us</a> at the moment.</p>

                <h3 class="mt-4">Community Guidelines</h3>
                <hr>
                Users have to use Lidarts' Services with the best intentions to ensure the best possible experience for everyone.
                Lidarts has the ultimate say to decide what behaviour is appropiate and reserves the right to ban or close User accounts
                without warning or the obligation to provide evidence that these guidelines have been breached.
                <p>The following list provides examples of what Users should certainly not do:</p>
                <p><strong>Cheating.</strong> Every online darts scoring service relies on trust. Games on Lidarts against other human beings
                    require every User to play honestly. Cheating includes entering wrong scores on purpose or not playing by the official rules.</p>
                <p><strong>Staging games and their results.</strong> Although not yet in use, Lidarts might measure the Users' playing strength
                    to improve the experience of the Services. Intentionally trading wins or losses to obfuscate your playing strength manipulates
                    this system.</p>
                <p><strong>Bad sportsmanship.</strong> Be respectful to other players. Do not harass, insult, spam or waste someone's time on purpose.
                </p>
                <p><strong>Impersonation.</strong> Registered Users may choose a publicly displayed username. Don't impersonate others, we
                    recommend you to use a recognizable pseudonym.</p>
                <p><strong>Publishing copyrighted material.</strong> Registered users can share their own content publicly and are responsible
                for everything related to these actions. It is illegal to share content you didn't create by yourself or you don't have the
                permission or right to share for.</p>
                <p><strong>Abuse Lidarts' infrastructure.</strong> Running the Services costs money, so we need to scale with care.
                    By putting unreasonable loads on our servers you might impair other Users' experience on our site. We reserve the right
                to determine what is reasonable.</p>
                <p><strong>Breaking into accounts or our servers.</strong> To protect us and our Users, we will report any illegal activity
                to authorities. You can help improving our security by <a href="{{ url_for('generic.contact') }}">reporting security issues</a>
                that you encounter to us.</p>

                <p>This list is non-exhaustive and just provides a few examples that we consider important for a peaceful community. We
                reserve the rights to decide what violates our guidelines and decide about appropriate penalization.</p>

                <h3 class="mt-4">Privacy</h3>
                <hr>
                <p>Our <a href="{{ url_for('legal.privacy') }}">privacy policy</a> describes how we handle the information you provide to us when you use our services.
                    You understand that through your use of the Services you consent to the collection and use (as set forth in the Privacy Policy) of this information.
                    Lidarts follows the European Union and German data protection laws and applies these to all users worldwide.</p>

                <h3 class="mt-4">Copyright</h3>
                <hr>
                <p>Lidarts is licensed under the <a href="https://github.com/mischkadb/lidarts/blob/master/LICENSE">GNU AGPL license.</a></p>

                <p>Lidarts respects the intellectual property rights of others and expects Users of the Services to do the same.
                    Lidarts reserves the right to remove content alleged to be infringing without prior notice at our sole discretion
                    and without liability to you. We will respond to notices of alleged copyright infringement
                    that comply with applicable law and are properly provided to us.</p>

                <p> If you believe your content has been copied in a way that constitutes copyright infringement
                    or your intellectual property rights have been otherwise violated, please alert us by contacting us at contact@lidarts.org.</p>

                <p>You retain your rights to any content you submit, post or display on or through the services.
                    By submitting, posting or displaying content on or through our services, you grant us a global, non-exclusive,
                    royalty-free license - with the right to sublicense - to use, copy, reproduce, process, adapt, modify, publish,
                    transmit, display and distribute such content in any and all media or distribution channels.</p>

                <h3 class="mt-4">Our rights</h3>
                <hr>
                <p>To operate, we need to be able to maintain control over what happens on our website.
                    We reserve the right to make decisions to protect the health and integrity of our system.
                    We don’t take these powers lightly, and we only use them when we absolutely have to.</p>

                <p>We can make changes to the Lidarts Site and Services without notice or liability for any loss, damage
                or harm that might result from these changes.</p>
                <p> We have the right to decide who’s eligible to use Lidarts. We can cancel accounts or decline to offer our Services.
                   We can change our eligibility criteria at any time.</p>
                <p>We are not responsible for any loss, damage or harm caused by downtimes or disfunctions of our Site or Services.</p>


                <h3 class="mt-4">Limitation of Liability</h3>
                <hr>
                <p>Our Services are provided to you “as is” and “as available” and without warranty of any kind, express or implied. </p>
                <p>We are not responsible for any harm, damage or loss caused by errors in or availability of our Services.
                We cannot be held responsible for any loss caused by third party sources.</p>
                <p>No advice or information (oral or written) obtained by you from Lidarts entities or through Lidarts services
                    shall create any warranty.</p>

                <h3 class="mt-4">Jurisdiction</h3>
                <hr>
                <p>Lidarts is based in Germany, so you agree to accept the law and jurisdiction of Germany by using our services.</p>
                <p>We encourage you to contact us if you have any dispute with us, so we can resolve the dispute out of court.</p>
                <p>In the event any provision of these Terms is held to be invalid or unenforceable, such provision will be severed
                    from the remainder of these Terms, and such remainder will remain in force and effect.</p>




            </div>
        </div>
    </div>
</div>




{% endblock %}